BE-2: crud operations of team are added
GDG-Baku/ms-team pull request #6
Opened 2020-03-18 09:51 UTC by asifhajiyev

2020-03-25 13:16 UTC, NigarMovsumova requested changes

2020-03-25 13:16 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/controller/MemberController.java
> +public class MemberController {
TeamController is more readable for the purposes of this service.

2020-03-25 13:16 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/controller/MemberController.java
> +@RequestMapping("members")
/

2020-03-25 13:16 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/controller/MemberController.java
> +    private MemberServiceImpl memberService;
Use interface instead

2020-03-25 13:16 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/controller/MemberController.java
> +    @PostMapping
why not internal ?

2020-03-25 13:16 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/model/entity/Member.java
> +public class Member {
MemberEntity

2020-03-25 13:16 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +    MemberRepository memberRepository;
private!

2020-03-25 13:16 UTC, NigarMovsumova commented on src/main/resources/db/changelog/changelog-master.yml
> +      file: db/changelog/1.0/changelog-insert-data-1.0.1.yml
no need for such long names, just version : changelog-1.0.1.yml for example.

2020-03-25 13:16 UTC, NigarMovsumova commented on src/main/resources/db/changelog/1.0/changelog-insert-data-1.0.1.yml
> +                  value: "Mammadzada"
delete him with liquibase.

2020-03-25 13:30 UTC, NigarMovsumova requested changes

2020-03-25 13:30 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +    public List<MemberDto> getAllMembers() {
why? Just retrieve the list from repository and throw exception if nothing is found. Do not overcomplicate. Review my code to see how it is done.

2020-03-25 13:30 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +        isValid = true;
I believe, you don't need this field here.

2020-03-25 13:30 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +        } catch (MemberNotFoundException e) {
Why are you catching the same exception if you are already throwing it in try block ?

2020-03-25 13:30 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +            member = memberRepository.findById(id).orElseThrow(() -> new MemberNotFoundException("Member doesn't exist with this id"));
add id to exception, so it is easier for you to understand the problem from logs. You did not add any logs, why ?

2020-03-25 13:30 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +    private String isMemberValid(MemberDto memberDto) {
I have validation example in one or two of my repositories, please change it according to my examples.

2020-03-25 18:54 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +        } catch (MemberNotFoundException e) {
extend your exception from RuntimeException for now.

2020-03-31 18:02 UTC, NigarMovsumova requested changes

2020-03-31 18:02 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/controller/MemberController.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(MemberController.class);
logger should be lowercase

2020-03-31 18:02 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/exception/MemberAlreadyExistException.java
> +public class MemberAlreadyExistException extends RuntimeException {
refactor class name

2020-03-31 18:02 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/model/dto/MemberDto.java
> +    //@NotBlank(message = "First name cannot be empty")
removed unused code comments

2020-03-31 18:02 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(MemberServiceImpl.class);
lowercase

2020-03-31 18:02 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +        LOGGER.info("ActionLog.createMember.start");
add some params to logs, for example memberDto.getEmail(), because it will be useful if you are looking at the logs (easier to find where is the problem)

2020-03-31 18:02 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +
are you sure you need both of these logs ?

2020-03-31 18:02 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +    }
Why do you need this method ?

2020-03-31 18:02 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/model/entity/MemberEntity.java
> +    private Integer id;
Long

2020-03-31 18:02 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/model/dto/MemberDto.java
> +//@MemberConstraint
?

2020-03-31 18:02 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/util/CheckViolationHelper.java
> +@NoArgsConstructor
add it as a constructor, no need for this annotation here. You should use it when you have class with several fields.

2020-03-31 18:02 UTC, NigarMovsumova commented on src/main/resources/db/changelog/1.0/changelog-1.0.1.yml
> +                  value: "1"
can it give an id automatically?

2020-03-31 18:11 UTC, asifhajiyev commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +    }
I use this method only inside the service layer to get MemberEntity

2020-03-31 18:17 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +    }
Why do not you directly just call the repository method ? There is no point in having this method, because it just logs the start

2020-03-31 19:00 UTC, asifhajiyev commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +    }
Done

2020-05-17 06:29 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/client/AuthenticationClient.java
> +@FeignClient(value = "ms-auth-client", url = "https://gdg-ms-auth.herokuapp.com/")
url should be in resources, yml file

2020-05-17 06:29 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/MemberService.java
> +    String createMember(MemberDto memberDto);
we have talked about it...

2020-05-17 06:29 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/MemberService.java
> +    MemberDto getMemberById(Long id);
?

2020-05-17 06:29 UTC, NigarMovsumova commented on src/main/java/az/gdg/msteam/service/impl/MemberServiceImpl.java
> +            memberEntity.setPhoto(memberDto.getPhoto());
in separate method

2020-08-11 18:23 UTC, merged